name = "Coding Dojo"
license = "GPL"
licenselink = "https://github.com/codingdojo-org/template-hugo-codingdojo/blob/master/LICENSE.md"
description = "An homemade hugo template."
homepage = "https://github.com/codingdojo-org/template-hugo-codingdojo"
tags = ["documentation", "docs", "responsive"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"

